name: CI/CD - Build & Deploy with ArgoCD

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: pachipico/test
  HELM_REPO_URL: https://github.com/pachipico/miro-sys.git
  HELM_REPO_PATH: environment/dev/values.yaml
  TARGET_BRANCH: main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    environment: miro-test

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_TEST_USERNAME }}
          password: ${{ secrets.DOCKER_TEST_TOKEN }}

      - name: Extract short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push image
        run: |
          docker build -t $IMAGE_NAME:${{ steps.vars.outputs.SHORT_SHA }} .
          docker push $IMAGE_NAME:${{ steps.vars.outputs.SHORT_SHA }}

  update-helm-and-trigger:
    name: Update Helm Chart and Trigger ArgoCD
    runs-on: ubuntu-latest
    needs: build-and-push
    environment: miro-test

    steps:
      - name: Clone Helm chart repo
        uses: actions/checkout@v3
        with:
          repository: pachipico/miro-sys
          token: ${{ secrets.TEST_TOKEN }}
          path: environment/dev

      - name: Update image tag in Helm values
        run: |
          sed -i "s/tag: .*/tag: '${{ steps.vars.outputs.SHORT_SHA }}'/" $HELM_REPO_PATH

  #     - name: Commit and push
  #       run: |
  #         cd helm-repo
  #         git config user.name "github-actions"
  #         git config user.email "github-actions@users.noreply.github.com"
  #         git add $HELM_REPO_PATH
  #         git commit -m "chore: update image tag to ${{ steps.vars.outputs.SHORT_SHA }}"
  #         git push origin $TARGET_BRANCH
